# https://docs.travis-ci.com/user/customizing-the-build/

branches:
  only:
    - master
language: node_js
node_js: 11.14.0
cache:
  yarn: true
env:
  global:
    - MOZ_HEADLESS=1 # needed for karma tests running in headless mode
jobs:
  include:
    - stage: 'Prepare web clients'
      os: linux
      dist: xenial
      addons:
        apt:
          packages:
            - libsecret-1-dev # needed for "keytar" native dependency installing/rebuilding
            - nasm # needed for protonmail / tutanota building (don't remember which one)
      cache:
        yarn: true
        directories:
          - output/git
      script: ./scripts/travis/prepare-webclients.sh
    - stage: 'Build app'
      os: windows
      # TODO travis cache: C\:\\Users\travis\\AppData\\Local\\Yarn\\Cache: Cannot stat: No such file or directory
      cache: false
      env:
        # prevent the following error: No output has been received in the last 10m0s
        # https://travis-ci.community/t/build-doesnt-finish-after-completing-tests/288/9
        - YARN_GPG=no
      before_install:
        - powershell Get-Process
        # enable running local PowerShell scripts
        - powershell -Command 'Set-ExecutionPolicy -ExecutionPolicy RemoteSigned'
        - | # tackle the performance issue of "yarn install" execution, see https://travis-ci.community/t/current-known-issues-please-read-this-before-posting-a-new-topic/264/15
          export NODEPATH=$(where.exe node.exe)
          export PROJECTDIR=$(pwd)
          export YARNCACHE=$(yarn cache dir)
          export TEMPDIR=$LOCALAPPDATA\\Temp
          powershell Add-MpPreference -ExclusionProcess ${NODEPATH}
          powershell Add-MpPreference -ExclusionPath ${YARNCACHE}
          powershell Add-MpPreference -ExclusionPath ${PROJECTDIR}
          powershell Add-MpPreference -ExclusionPath ${TEMPDIR}
          echo "DisableArchiveScanning..."
          powershell Start-Process -PassThru -Wait PowerShell -ArgumentList "'-Command Set-MpPreference -DisableArchiveScanning \$true'"
          echo "DisableBehaviorMonitoring..."
          powershell Start-Process -PassThru -Wait PowerShell -ArgumentList "'-Command Set-MpPreference -DisableBehaviorMonitoring \$true'"
          echo "DisableRealtimeMonitoring..."
          powershell Start-Process -PassThru -Wait PowerShell -ArgumentList "'-Command Set-MpPreference -DisableRealtimeMonitoring \$true'"
        - choco install --yes googlechrome
        - echo $(where.exe node.exe)
        - echo $(yarn cache dir)
      before_script:
        - powershell Get-Process
      script: ./scripts/travis/script-windows.sh
      after_script:
        - powershell Get-Process
    - stage: 'Build app'
      os: osx
      osx_image: xcode9.4
      addons:
        firefox: latest
      script: ./scripts/travis/script-osx.sh
    - stage: 'Build app'
      os: linux
      # TODO use "xenial" dist; e2e tests doesn't work (auto login using "node-keytar" case)
      # https://travis-ci.community/search?q=No%20output%20has%20been%20received%20in%20the%20last%20windows%20category%3A16
      dist: trusty
      group: stable
      sudo: required
      services:
        - docker
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test # upgrade GCC to a more recent version, see https://docs.travis-ci.com/user/languages/cpp/#gcc-on-linux
          packages:
            - g++-7 # needed for native modules compiling/rebuilding
            - libsecret-1-dev # needed for "keytar" native dependency installing/rebuilding
            - gnome-keyring # needed for initializing keychain for running e2e tests that use "keytar"
            - libgnome-keyring-dev # needed for initializing keychain for running e2e tests that use "keytar"
            - python-gnomekeyring # needed for initializing keychain for running e2e tests that use "keytar"
        firefox: latest
      before_script:
        - | # needed for native modules compiling/rebuilding
          export CC=gcc-7 CXX=g++-7;
        - | # init xvfb
          export DISPLAY=:99.0;
          sh -e /etc/init.d/xvfb start;
          sleep 3;
        - | # init dbus
          NO_AT_BRIDGE=1;
          eval $(dbus-launch --sh-syntax);
        - | # init keychain
          eval $(echo -n "" | /usr/bin/gnome-keyring-daemon --login);
          eval $(/usr/bin/gnome-keyring-daemon --components=secrets --start);
          /usr/bin/python -c "import gnomekeyring;gnomekeyring.create_sync('login', '');";
      script: ./scripts/travis/script-linux.sh
before_install:
  - | # installing the most recent yarn version
    curl -o- -L https://yarnpkg.com/install.sh | bash;
    export PATH="$HOME/.yarn/bin:$PATH";
install:
  - npx envinfo
  - node --version
  - npm --version
  - yarn --version
  - yarn install --pure-lockfile --network-timeout 1000000
after_failure:
  - tar -cvf e2e-logs.tar ./output/e2e
  - yarn scripts/transfer upload e2e-logs.tar
notifications:
  email:
    on_success: never
    on_failure: change
